### ISSUE TITLE
Driver data for core NGEE sites

### ISSUE THREAD

**Issue by serbinsh** [fmyuan/pt-e3sm-inputdata#2]
@fmyuan regarding the NGEE modeling workshop, I was wondering if we could get the inputs needed to run OLMT simulations at all the core NGEE sites: US-Brw/Utqiagvik, Council, Kougarok Mile 64, and Teller Mile 27?  

Thus far we have what we need to run Kougarok.  I was also able to setup a non dynpft version of Brw like this

```
docker run -t -i --hostname=docker --user modeluser -v elmdata:/inputdata -v elmoutput_custom_run:/output \
fasstsimulation/elm-builds:elm_v2-for-ngee bin/bash -c 'cd /tools/OLMT && python3 ./site_fullrun.py \
--site AK-BEOG --sitegroup NGEEArctic --caseidprefix OLMT \
--nyears_ad_spinup 20 --nyears_final_spinup 50 --tstep 1 \
--machine docker --compiler gnu --mpilib openmpi \
--cpl_bypass --gswp3 \
--model_root /E3SM \
--caseroot /output \
--ccsm_input /inputdata \
--runroot /output \
--spinup_vars \
--nopointdata \
--nopftdyn \
--metdir /inputdata/atm/datm7/1x1pt_US-Brw/cpl_bypass_GSWP3 \
--domainfile /inputdata/share/domains/domain.clm/domain.lnd.1x1pt_US-Brw_navy.nc \
--surffile /inputdata/lnd/clm2/surfdata_map/surfdata_1x1pt_US-Brw_simyr1850_c360x720_c20190221.nc \
&& sleep 10 \
&& cd /output/cime_run_dirs/OLMT_AK-BEOG_ICB20TRCNPRDCTCBC/run \
&& ncrcat --ovr *.h0.*.nc ELM_output.nc \
&& chmod 777 ELM_output.nc'
```

But I was thinking we might want consistent inputs/examples across all sites?   Is that easy to do?  Then we can use the existing script to pull down these data for the attendees

**Comment by fmyuan** [comment]
I have those datasets generated already. Let me put them into the repository in a consistent way, so that we probably can run fewer scripts as much as possible.

**Comment by serbinsh** [comment]
Perfect, thank you!!  Yes simplifying the scripts using a consistent hierarchy would be great

**Comment by serbinsh** [comment]
@fmyuan Thinking about it more, if we refactor the drivers for teh workshop a little we could use a single script to setup an OLMT run at any of this sites using a script embedded in the docker container like this

```
for i in "$@"
do
case $i in
    -sn=*|--site_name=*)
    site_name="${i#*=}"
    shift # past argument=value
    ;;
    -sg=*|--site_group=*)
    site_group="${i#*=}"
    shift # past argument=value
    ;;
    -cp=*|--case_prefix=*)
    case_prefix="${i#*=}"
    shift # past argument=value
    ;;
    -adsy=*|--ad_spinup_years=*)
    ad_spinup_years="${i#*=}"
    shift # past argument=value
    ;;
    -fsy=*|--final_spinup_years=*)
    final_spinup_years="${i#*=}"
    shift # past argument=value
    ;;
    -tsp=*|--timestep=*)
    timestep="${i#*=}"
    shift # past argument=value
    ;;
    *)
        # unknown option
    ;;
esac
done
# =======================================================================================

# =======================================================================================
# Set defaults and print the selected options back to the screen before running
site_name="${site_name:-AK-K64G}"
site_group="${site_group:-NGEEArctic}"
case_prefix="${case_prefix:-OLMT}"
ad_spinup_years="${ad_spinup_years:-200}"
final_spinup_years="${final_spinup_years:-600}"
timestep="${timestep:-1}"

# print back selected or set options to the user
echo " "
echo " "
echo "*************************** OLMT run options ***************************"
echo "Site Name = ${site_name}"
echo "Site Group = ${site_group}"
echo "Case Prefix = ${case_prefix}"
echo "Number of AD Spinup Simulation Years = ${ad_spinup_years}"
echo "Number of Final Spinup Simulation Years = ${final_spinup_years}"
echo "Model Timestep = ${timestep}"

# pause to show options before continuing
sleep 3
# =======================================================================================

# =======================================================================================
# create the OLMT run command
if python3 ./site_fullrun.py \
      --site ${site_name} --sitegroup ${site_group} --caseidprefix ${case_prefix} \
      --nyears_ad_spinup ${ad_spinup_years} --nyears_final_spinup ${final_spinup_years} \
      --tstep ${timestep} --machine docker --compiler gnu --mpilib openmpi \
      --cpl_bypass --gswp3 \
      --model_root /E3SM \
      --caseroot /output \
      --ccsm_input /inputdata \
      --runroot /output \
      --spinup_vars \
      --nopointdata \
      --metdir /inputdata/atm/datm7/atm_forcing.datm7.GSWP3.0.5d.v2.c180716_kougarok-Grid/cpl_bypass_full \
      --domainfile /inputdata/share/domains/domain.clm/domain.lnd.1x1pt_kougarok-GRID_navy.nc \
      --surffile /inputdata/lnd/clm2/surfdata_map/surfdata_1x1pt_kougarok-GRID_simyr1850_c360x720_171002.nc \
      --landusefile /inputdata/lnd/clm2/surfdata_map/landuse.timeseries_1x1pt_kougarok-GRID_simyr1850-2015_c180423.nc \
      & sleep 10

# TODO! need to modify the names of the site driver data so that they are easily switched using the ${site_name}
# e.g. --metdir /inputdata/atm/datm7/atm_forcing.datm7.GSWP3.0.5d.v2.c180716_${site_name}-Grid/cpl_bypass_full
# --domainfile /inputdata/share/domains/domain.clm/domain.lnd.1x1pt_${site_name}-GRID_navy.nc
# --surffile /inputdata/lnd/clm2/surfdata_map/surfdata_1x1pt_${site_name}-GRID_simyr1850_c360x720_171002.nc
# --landusefile /inputdata/lnd/clm2/surfdata_map/landuse.timeseries_1x1pt_${site_name}-GRID_simyr1850-2015_c180423.nc

then
  wait

  echo "DONE docker ELM runs !"

else
  exit &?
fi
```

then when we run the script we pass arguments like --site_name AK-K64G or whatever and that gets passed to OLMT and if the drivers are named consistently then that argument gets used to select from the correct site driver data.  Make sense?  Then we dont need a script for each site, we just have the users input the site they want at runtime

**Comment by serbinsh** [comment]
```
10-4-5-251:~ sserbin$ docker run -t -i --hostname=docker --user modeluser -v elmdata:/inputdata -v /Users/sserbin/scratch/elm_testruns/testing:/output \
> -v /Users/sserbin/Data/GitHub/fasst_simulation_tools/elm_scripts/ngeearctic_elm_scripts/olmt_scripts:/scripts \
> fasstsimulation/elm-builds:elm_v2-for-ngee-serial /scripts/ngeearctic_site_fullrun_userdata_docker.sh --site_name=AK-K64G \
> --ad_spinup_years=25 --final_spinup_years=50


*************************** OLMT run options ***************************
Site Name = AK-K64G
Site Group = NGEEArctic
Case Prefix = OLMT
Number of AD Spinup Simulation Years = 25
Number of Final Spinup Simulation Years = 50
Model Timestep = 1
2014 2015
mkdir -p temp
mkdir -p scripts/OLMT
```

**Comment by fmyuan** [comment]
There is a very simple way to change site name, by passing the name into bash script. I will update the script in OLMT example.

**Comment by serbinsh** [comment]
@fmyuan OK.  I guess to me the way the script is setup the associated driver data are hard coded to Kougarok. In the example I provided I was thinking we could create this more general example that will work for all of our core sites

**Comment by fmyuan** [comment]
Just sort of make the naming consistent for all 4 sites, in this data repository.

**Comment by serbinsh** [comment]
Oh ok...what about the other options I added to the example above where we can select AD/final spinup years etc?  Think it would be good if a user could change just a few of the main options for a basic run.  

Think this is something we can discuss in terms of simplifying but also enabling more options, including pointing to custom params and inputs

**Comment by serbinsh** [comment]
@fmyuan we need to chat today about the changes to the drivers.  This is creating errors in our existing examples 

```
Using protocol wget with user  and passwd
Using protocol svn with user  and passwd
Client protocol None not enabled
Checking server https://web.lcrc.anl.gov/public/e3sm/inputdata/ with protocol wget
Using protocol wget with user  and passwd
Loading input file list: 'Buildconf/mosart.input_data_list'
Loading input file list: 'Buildconf/elm.input_data_list'
Model elm no file specified for finidat
Model elm missing file fsurdat = '/inputdata/lnd/clm2/surfdata_map/surfdata_1x1pt_kougarok-GRID_simyr1850_c360x720_171002.nc'
Trying to download file: 'lnd/clm2/surfdata_map/surfdata_1x1pt_kougarok-GRID_simyr1850_c360x720_171002.nc' to path '/inputdata/lnd/clm2/surfdata_map/surfdata_1x1pt_kougarok-GRID_simyr1850_c360x720_171002.nc' using WGET protocol.
wget failed with output:  and errput --2022-08-10 17:15:35--  https://web.lcrc.anl.gov/public/e3sm/inputdata/lnd/clm2/surfdata_map/surfdata_1x1pt_kougarok-GRID_simyr1850_c360x720_171002.nc
Resolving web.lcrc.anl.gov (web.lcrc.anl.gov)... 140.221.70.30
Connecting to web.lcrc.anl.gov (web.lcrc.anl.gov)|140.221.70.30|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-08-10 17:15:35 ERROR 404: Not Found.

Loading input file list: 'Buildconf/cpl.input_data_list'
Checking server https://svn-ccsm-inputdata.cgd.ucar.edu/trunk/inputdata with protocol svn
Using protocol svn with user  and passwd
Loading input file list: 'Buildconf/mosart.input_data_list'
Loading input file list: 'Buildconf/elm.input_data_list'
Model elm no file specified for finidat
Model elm missing file fsurdat = '/inputdata/lnd/clm2/surfdata_map/surfdata_1x1pt_kougarok-GRID_simyr1850_c360x720_171002.nc'
Trying to download file: 'lnd/clm2/surfdata_map/surfdata_1x1pt_kougarok-GRID_simyr1850_c360x720_171002.nc' to path '/inputdata/lnd/clm2/surfdata_map/surfdata_1x1pt_kougarok-GRID_simyr1850_c360x720_171002.nc' using SVN protocol.
svn export failed with output:  and errput svn: E170000: URL 'https://svn-ccsm-inputdata.cgd.ucar.edu/trunk/inputdata/lnd/clm2/surfdata_map/surfdata_1x1pt_kougarok-GRID_simyr1850_c360x720_171002.nc' doesn't exist

Loading input file list: 'Buildconf/cpl.input_data_list'
Checking server None with protocol None
Client protocol None not enabled
ERROR: Could not find all inputdata on any server
cp: cannot stat '/output/cime_run_dirs/OLMT_AK-K64G_ICB1850CNRDCTCBC_ad_spinup/run//OLMT_AK-K64G_ICB1850CNRDCTCBC_ad_spinup.elm.r.0081-01-01-00000.nc': No such file or directory
chmod: cannot access '/output/cime_run_dirs/OLMT_AK-K64G_ICB1850CNRDCTCBC_ad_spinup/run//OLMT_AK-K64G_ICB1850CNRDCTCBC_ad_spinup.elm.r.0081-01-01-00000.nc.orig': No such file or directory
Traceback (most recent call last):

```

I expected this but we need to decide final structure and creating updated version of the run examples. Again if we can use a consistent naming we should be able to make 1 script that can run at any of the 4 sites

**Comment by fmyuan** [comment]
need to modify example scripts slightly - having moved data around so that 4 sites are in one places, like, for sitename=kougarok:

      --metdir /inputdata/atm/datm7/atm_forcing.datm7.GSWP3.0.5d.v2.c180716_NGEE-Grid/cpl_bypass_${sitename} \
      --domainfile /inputdata/share/domains/domain.clm/domain.lnd.1x1pt_${sitename}-GRID_navy.nc \
      --surffile /inputdata/lnd/clm2/surfdata_map/surfdata_1x1pt_${sitename}-GRID_simyr1850_c360x720_c171002.nc \
      --landusefile /inputdata/lnd/clm2/surfdata_map/landuse.timeseries_1x1pt_${sitename}-GRID_simyr1850-2015_c180423.nc \

**Comment by fmyuan** [comment]
For 4 sites, names are: kougarok, teller, council, beo, respectively.

**Comment by serbinsh** [comment]
Ok.  Wasn’t sure if I needed to use the names in the NGEE site text file in PT CLM or the names you gave the directories

[iphone]

On Aug 10, 2022, at 13:34, Fengming Yuan ***@***.***> wrote:

﻿

For 4 sites, names are: kougarok, teller, council, beo, respectively.

**Comment by fmyuan** [comment]
--nopointdata is the key. If this option is on (true), OLMT will pick up name from PTCLM/NGEEArctic_sitedata.txt, (and associated lat/lon point). The options --metdir, --surffile, --landusefile, --domainfile, will be ignored. OLMT will then automatically produce all those input files and stored in RUN Directory. Otherwise, OLMT will skip 'makepointdata' step, and directly over-ride relevant data files using provided.

**Comment by fmyuan** [comment]
So, when running in assembly-mode, must remove '--nopointdata' option. In this case, the inputdata folder must have global datasets for those to extract.

**Comment by fmyuan** [comment]
you may noticed that I edited the wiki page, relevant to data path changing, in your fasst_simulation_tools repo. Let me know if work as expected.

**Comment by serbinsh** [comment]
@fmyuan It looks like the changes here and the modified run script are working.  However I did find one issue with the met driver filenames.  It looks like most of the landuse files are named the same, except BEO.  E.g. 

surfdata_map/landuse.timeseries_1x1pt_teller-GRID_simyr1850-2015_c180423.nc

vs

landuse.timeseries_1x1pt_beo-GRID_simyr1850-2015_c360x720_c180423.nc

Note that the BEO file has "c360x720" in it but the others do not.  Is it easy to modify the BEO file to be consistent?  Then I think we are good.  But I will need to do a bit more testing to be sure and see a run fully complete

Thanks!
